name: Build and Publish

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: "0 13 * * 1"

jobs:
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    permissions:
      id-token: write
      contents: write
      security-events: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_IMAGE }}:latest .
      
      - name: Run image tests
        run: |
          docker run --rm -p 8000:8000 -d ${{ secrets.DOCKER_HUB_IMAGE }}:latest python -m http.server 8000
          sleep 5
          curl -I --fail localhost:8000

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ secrets.DOCKER_HUB_IMAGE }}:latest'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Docker push image to DockerHub
        run: |
          docker push ${{ secrets.DOCKER_HUB_IMAGE }}:latest
